#!/usr/bin/env python
import sys
import re
import wget
import boto3
import threading
import time
from botocore.exceptions import ClientError

def s3_get(bucket,file):
    client = boto3.client('s3')
    resource = boto3.resource('s3',
        aws_access_key_id='AKIAIOGAUN4GEYTK6LFA',
        aws_secret_access_key= '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')
    my_bucket = resource.Bucket(bucket)
    print "=> Downloading: ", file 
    my_bucket.download_file(file, file)
    return
    
def main(x):
    print(threading.current_thread().getName(), 'Starting')
    match = re.search(r'^s3:', x)
    if match:
        bucket, filename=x.strip("s3://").split("/")
        s3_get(bucket,filename)
    else:
        print "=> Downloading: ", x
        filename = wget.download(x)
        
    print(threading.current_thread().getName(), 'Exiting')
        
## Main loop
threads = []
for x in sys.argv[1:]:
    t = threading.Thread(target=main, args=(x,))
    threads.append(t)
    t.start()